import Head from 'next/head'
import Layout from '../components/layout'
import Nests from '../components/nests'
import { queryNests, useNests } from 'graphql/queries/useNests'
import { queryBirds, useBirds } from 'graphql/queries/useBirds'
import { queryFamilies, useFamilies } from 'graphql/queries/useFamilies'

export default function Home({ nests, birds, families }) {
  const { data: graphQlNests } = useNests(nests)
  const { data: graphQlBirds } = useBirds(birds)
  const { data: graphQlFamilies } = useFamilies(families)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Nests
          nests={graphQlNests}
          birds={graphQlBirds}
          families={graphQlFamilies}
        />
      </Layout>
    </div>
  )
}

export async function getStaticProps(_) {
  const nests = await queryNests()
  const birds = await queryBirds()
  const families = await queryFamilies()
  return { props: { nests, birds, families } }
}
